package com.example.myapplication

data class MoodEntry(
    val id: Long = 0, // Unique ID for each entry, 0 for new entries (will be auto-generated by DB)
    val userId: Int, // Foreign key to link to the User table
    val date: String, // Date of the entry (e.g., "YYYY-MM-DD")
    val title: String, // Title of the diary entry
    val content: String // The main content/body of the diary entry
)